name: cd

on:
  workflow_dispatch:
    inputs:
      sha:
        description: The commit SHA on which the new version was found
        required: true
      version:
        description: The new version to publish
        required: true

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.sha }}
          fetch-depth: 1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build
        run: ./gradlew hostSpecificBuild

      - name: Publish
        run: ./gradlew hostSpecificPublish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  github_release:
    name: Create a github release
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - name: Create github release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: ${{ github.event.inputs.sha }}
          tag_name: ${{ github.event.inputs.version }}
