name: cd

on:
  workflow_dispatch:
    types: [ new-version ]

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
          fetch-depth: 1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build
        run: ./gradlew hostSpecificBuild

      - name: Publish
        run: ./gradlew hostSpecificPublish

  github_release:
    name: Create a github release
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - name: Create github release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: ${{ github.event.client_payload.sha }}
          tag_name: ${{ github.event.client_payload.version }}
